import java.util.ArrayList;
/**
 * 
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose 
 * values do not exceed four million, find the sum of the even-valued terms.

 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Fibonacci
{
    

    public Fibonacci()
    {
        ArrayList<Integer> fibbArrayList = new ArrayList<Integer>(0);
        fibbArrayList.add(1);
        fibbArrayList.add(2);
        for (int i = 0; i< 999999; i++)
        {
            int newnumber = fibbArrayList.get(i)+fibbArrayList.get(i+1);
            if(newnumber > 4000000)
            {
                break;
            }
            fibbArrayList.add(newnumber);
        }
        int sum = 0;
        for (int i = 0; i< fibbArrayList.size(); i++)
        {
            if (fibbArrayList.get(i)%2==0)
            {
                sum = sum + fibbArrayList.get(i);
            }
        }
        System.out.println(sum);
    }
}
